name: Go Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Go Application for Windows x64
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install dependencies
      run: go mod tidy

    - name: Build for Windows x64
      run: |
        go build -ldflags="-H windowsgui" -o ArishtiOverflow-windows-amd64.exe

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ArishtiOverflow-windows-amd64
        path: ArishtiOverflow-windows-amd64.exe
